"""add cta tables

Revision ID: 0cdb4c0a9f01
Revises: c9f1a2997b63
Create Date: 2026-05-02 11:31:03.056558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cdb4c0a9f01'
down_revision: Union[str, Sequence[str], None] = 'c9f1a2997b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cta_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('button_label', sa.String(), nullable=False),
    sa.Column('page_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cta_clicks_id'), 'cta_clicks', ['id'], unique=False)
    op.create_table('cta_enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('source_page', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('organization_name', sa.String(), nullable=True),
    sa.Column('material_type', sa.String(), nullable=True),
    sa.Column('line', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cta_enquiries_id'), 'cta_enquiries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cta_enquiries_id'), table_name='cta_enquiries')
    op.drop_table('cta_enquiries')
    op.drop_index(op.f('ix_cta_clicks_id'), table_name='cta_clicks')
    op.drop_table('cta_clicks')
    # ### end Alembic commands ###
