"""add button_label to cta_enquiry

Revision ID: 7a3e58753ef9
Revises: 0cdb4c0a9f01
Create Date: 2026-05-02 12:02:10.551240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3e58753ef9'
down_revision: Union[str, Sequence[str], None] = '0cdb4c0a9f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cta_enquiries', sa.Column('button_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cta_enquiries', 'button_label')
    # ### end Alembic commands ###
