"""Add AuditLog table

Revision ID: 8255cbfe6491
Revises: 36da4842e52e
Create Date: 2026-04-29 11:47:33.914991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8255cbfe6491'
down_revision: Union[str, Sequence[str], None] = '36da4842e52e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('process_time', sa.Float(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_level'), 'audit_logs', ['level'], unique=False)
    op.create_index(op.f('ix_audit_logs_service'), 'audit_logs', ['service'], unique=False)
    op.create_index(op.f('ix_audit_logs_source'), 'audit_logs', ['source'], unique=False)
    op.create_index(op.f('ix_audit_logs_time'), 'audit_logs', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_time'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_source'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_service'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_level'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
